-- generated by nhibernate from the code


    PRAGMA foreign_keys = OFF;

    drop table if exists "EmailRecipient";

    drop table if exists "Email";

    drop table if exists "EmailPart";

    drop table if exists HtmlEmailPart;

    drop table if exists VariableEmailPart;

    drop table if exists "EmailState";

    drop table if exists "Recipient";

    drop table if exists "EmailTemplate";

    drop table if exists "EmailTemplatePart";

    drop table if exists HtmlEmailTemplatePart;

    drop table if exists RepeatedSectionEmailTemplatePart;

    drop table if exists VariableEmailTemplatePart;

    drop table if exists "VariableType";

    drop table if exists "User";

    drop table if exists hibernate_unique_key;

    PRAGMA foreign_keys = ON;

    create table "EmailRecipient" (
        Id BIGINT not null,
       Sent BOOL not null,
       SentDate DATETIME,
       EmailId INT not null,
       RecipientId INT not null,
       primary key (Id),
       constraint FK_EmailRecipient_Email foreign key (EmailId) references "Email",
       constraint FK_EmailRecipient_Recipient foreign key (RecipientId) references "Recipient"
    );

    create table "Email" (
        Id INT not null,
       FromAddress TEXT,
       Subject TEXT,
       EmailTemplateId INT not null,
       EmailStateId INT not null,
       primary key (Id),
       constraint FK_Email_EmailTemplate foreign key (EmailTemplateId) references "EmailTemplate",
       constraint FK_Email_EmailState foreign key (EmailStateId) references "EmailState"
    );

    create table "EmailPart" (
        Id INT not null,
       Position INT,
       EmailId INT,
       primary key (Id),
       constraint FKB3CACEE7BB7A8FCD foreign key (EmailId) references "Email"
    );

    create table HtmlEmailPart (
        EmailPartId INT not null,
       Html TEXT not null,
       primary key (EmailPartId),
       constraint FKC187ECA4EAEB1497 foreign key (EmailPartId) references "EmailPart"
    );

    create table VariableEmailPart (
        EmailPartId INT not null,
       Value TEXT not null,
       VariableTypeId INT not null,
       primary key (EmailPartId),
       constraint FK5655592DEAEB1497 foreign key (EmailPartId) references "EmailPart",
       constraint FK_VariableEmailPart_VariableType foreign key (VariableTypeId) references "VariableType"
    );

    create table "EmailState" (
        Id INT not null,
       Name TEXT not null,
       CanSend BOOL not null,
       primary key (Id)
    );

    create table "Recipient" (
        Id INT not null,
       EmailAddress TEXT not null,
       Name TEXT not null,
       primary key (Id)
    );

    create table "EmailTemplate" (
        Id INT not null,
       Name TEXT,
       UserId INT not null,
       primary key (Id),
       FOREIGN KEY (UserId) REFERENCES User(id)
    );

    create table "EmailTemplatePart" (
        Id INT not null,
       Position INT,
       EmailTemplateId INT,
       primary key (Id),
       constraint FKC644F053C3BA1A19 foreign key (EmailTemplateId) references "EmailTemplate"
    );

    create table HtmlEmailTemplatePart (
        EmailTemplatePartId INT not null,
       Html TEXT not null,
       primary key (EmailTemplatePartId),
       constraint FKE07F3D8E8EBDE1D foreign key (EmailTemplatePartId) references "EmailTemplatePart"
    );

    create table RepeatedSectionEmailTemplatePart (
        EmailTemplatePartId INT not null,
       primary key (EmailTemplatePartId),
       constraint FK8A7C73968EBDE1D foreign key (EmailTemplatePartId) references "EmailTemplatePart"
    );

    create table VariableEmailTemplatePart (
        EmailTemplatePartId INT not null,
       Value TEXT not null,
       VariableTypeId INT not null,
       primary key (EmailTemplatePartId),
       constraint FK2A9FDCE18EBDE1D foreign key (EmailTemplatePartId) references "EmailTemplatePart",
       constraint FK_VariableEmailTemplatePart_VariableType foreign key (VariableTypeId) references "VariableType"
    );

    create table "VariableType" (
        Id INT not null,
       Name TEXT not null,
       primary key (Id)
    );

    create table "User" (
        Id INT not null,
       FirstName TEXT not null,
       LastName TEXT not null,
       EmailAddress TEXT not null,
       Password TEXT not null,
       primary key (Id)
    );

    create table hibernate_unique_key (
         next_hi INT 
    );

    insert into hibernate_unique_key values ( 1 );
