version: '3.4'

services:
  emailmaker.websitecore:
    image: ${DOCKER_REGISTRY}emailmakerwebsitecore
    build:
      context: .
      dockerfile: EmailMaker.WebsiteCore/Dockerfile.linux

  emailmaker.service:
    image: ${DOCKER_REGISTRY}emailmakerservice
    build:
      context: .
      dockerfile: EmailMaker.Service/Dockerfile.linux
